version: "3.8"

services:
  consul:
    image: consul:1.9.7
    container_name: consul-server
    ports:
      - "8500:8500"  # UI and HTTP API
      - "8600:8600/udp"  # DNS
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
  openresty:
    image: openresty/openresty:alpine
    depends_on: 
      - consul
    ports:
      - "8080:8080"
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./scripts:/usr/local/openresty/scripts
    command: /usr/local/openresty/nginx/sbin/nginx -g "daemon off;"
